name: JPacman CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    # Set up JDK 11
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    # Grant execute permission for gradlew
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    # Build with Gradle (Remove xvfb if not necessary)
    - name: Build with Gradle
      run: ./gradlew build  # Removed xvfb-run

    # Generate JaCoCo Badge
    - name: Generate JaCoCo Badge
      uses: cicirello/jacoco-badge-generator@v2
      with:
        badges-directory: .github/badges
        generate-coverage-badge: true
        coverage-badge-filename: jacoco.svg
        generate-branches-badge: true
        branches-badge-filename: branches.svg
        jacoco-csv-file: build/reports/jacoco/test/jacocoTestReport.csv  # Ensure this path is correct

    # Check badge creation
    - name: Check badge creation
      run: ls -l .github/badges

    # Commit changes (if badges are generated)
    - name: Commit changes
      uses: EndBug/add-and-commit@v9
      with:
        default_author: github_actions
        message: 'Updated JaCoCo badges'
        add: '.github/badges/*.svg'

    # Show test results (make sure JaCoCo is generating this CSV)
    - name: Show test results
      run: cat build/reports/jacoco/test/jacocoTestReport.csv  # Ensure the report exists at this path
